#!/bin/bash
zq(){
ls /etc/rc3.d/S* |cut -c 15-
echo -e "\033[33m这是显示本机开机启动服务的\033[0m \n"
}
zq

ip(){
ifconfig eth0 |grep "broadcast" |awk '{print $2}'
echo -e "\033[33m这是显示eth0的ip\033[0m\n"
}
ip

user(){
awk -F: '{sum[$7]++}END{for(i in sum){print sum[i] ,i}}' /etc/passwd
echo -e "\033[33m这是统计本机每种shell的用户的\033[0m\n"
}
user
 
fw(){
awk '{sum[$1]++}END{for (i in sum ){print sum[i],i}}' /etc/httpd/logs/access_log |sort -nr | sed -n '1,5p'
echo -e "\033[33m这是统计访问80端口次数最多的ip前5名\033[0m\n"
}
fw

