//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// <auto-generated>
//------------------------------------------------------------------------------

// Generated from: protos/c_table_achievement.proto
namespace TABLE
{
	public partial class ACHIEVEMENT
	{
		public int Id
		{
			get{ return (int)((id10_title14_rewards4 << 4) >> 22); }
		}

		public uint Title
		{
			get{ return (uint)((id10_title14_rewards4 << 14) >> 18); }
		}

		public uint Rewards
		{
			get{ return (uint)((id10_title14_rewards4 << 28) >> 28); }
		}
	}
}