//# generated by tools , Do Not Edit It ...
public enum ECM
{
	BEGIN = 0x100,//用户相关的包
	Connect = 101,        //连接服务器
	Disconnect,     //正常断线
	ConnectFail,        //连接失败

	#region heart
	ReqHeartbeatMessage = 100101,						//心跳请求
	ResHeartbeatMessage = 100102,						//心跳响应
	#endregion
	#region user
	ReqLoginMessage = 101101,						//登录请求
	ResLoginMessage = 101102,						//登录返回
	ReqCreateRoleMessage = 101104,						//创建角色
	ReqRandomRoleNameMessage = 101105,						//请求随机名字
	ResRandomRoleNameMessage = 101106,						//返回随机名字
	ReqChooseRoleMessage = 101107,						//选择角色进入游戏
	ResPlayerInfoMessage = 101108,						//角色信息
	ReqDeleteRoleMessage = 101109,						//删除角色请求
	ResDeleteRoleMessage = 101110,						//删除角色响应
	ResPlayAttributeChangedMessage = 101111,						//玩家属性改变
	ResPlayerEquipChangedMessage = 101112,						//玩家模型改变
	ReqBackToChooseRoleMessage = 101113,						//返回选角色界面
	ReqLogoutMessage = 101114,						//登出请求
	ResLoginAnotherSessionMessage = 101115,						//在其他地方登录
	ReqReconnectMessage = 101116,						//重新连接请求
	ResDisconnectMessage = 101117,						//断线响应
	ReqUserFeedbackMessage = 101118,						//用户反馈请求
	ReqBindPhoneNumberMessage = 101119,						//绑定手机号请求
	ReqUserCheatSpeedMessage = 101120,						//玩家使用加速器记录
	ReqRechargeMessage = 101121,						//充值消息请求
	ReqPushMessageMessage = 101122,						//推送消息消息请求
	ResPushMessageMessage = 101123,						//推送消息消息响应
	ReqUseInvitationCodeMessage = 101124,						//使用邀请码请求
	ResExtractInvitationCodeMessage = 101125,						//提取邀请码响应
	ResLoginSignTimeoutMessage = 101127,						//登录sign过期
	CheckCreateRoleArgsVaildReqMessage = 101128,						//创建角色检测角色参数请求
	CheckCreateRoleArgsVaildAckMessage = 101129,						//创建角色检测角色参数回应
	ServerTimeNtfMessage = 101130,						//服务器时间(选角下发)
	ServerLoadNtfMessage = 101131,						//系统负载通知
	ServerBusyNtfMessage = 101132,						//系统繁忙通知
	CreateRoleNtfMessage = 101133,						//创建角色反馈
	SCPlayerMoveSpeedMessage = 101140,						//玩家移动速度
	SCRoleListMessage = 101142,						//玩家角色列表
	#endregion
	#region map
	ReqEnterMapMessage = 102101,						//请求登录场景
	ResEnterMapMessage = 102102,						//返回登录场景
	ResUpdateViewMessage = 102103,						//更新视野
	ResObjectExitViewMessage = 102104,						//对象离开视野
	ResPlayerEnterViewMessage = 102105,						//玩家进入视野
	ResMonsterEnterViewMessage = 102106,						//怪物进入视野
	ReqPlayerMoveMessage = 102107,						//玩家移动请求
	ResObjectMoveMessage = 102108,						//物体移动
	ResItemEnterViewMessage = 102109,						//物品进入视野
	ResNPCEnterViewMessage = 102110,						//NPC进入视野
	ResPositionChangeMessage = 102111,						//同地图传送
	ResChangeMapMessage = 102112,						//即将切换地图消息
	ReqPlayerWalkMessage = 102113,						//玩家走路请求
	ResAdjustPositionMessage = 102114,						//纠正位置
	ReqReliveMessage = 102115,						//请求复活
	ResReliveMessage = 102116,						//复活响应
	ResPlayerHPChangedMessage = 102117,						//玩家hp/mp改变
	ResBufferEnterViewMessage = 102118,						//buffer进入视野
	ReqTransferMessage = 102119,						//传送请求
	ResItemsDropMessage = 102120,						//物品掉落
	ResItemOwnerChangedMessage = 102121,						//地面上的物品改变所属
	ReqTransferByDeliverConfigMessage = 102122,						//根据配置传送请求
	ResPetEnterViewMessage = 102123,						//宠物,法神进入视野
	ResGuardEnterViewMessage = 102124,						//守卫进入视野
	ResPetStateChangedMessage = 102125,						//神兽状态改变
	ResTriggerEnterViewMessage = 102126,						//触发器进入视野
	ResObjectChangePositionMessage = 102127,						//物体瞬移
	ResBossOwnerChangedMessage = 102129,						//boss所属改变
	ResBoxEnterViewMessage = 102131,						//宝箱进入视野
	ReqBoxOperatelMessage = 102132,						//宝箱操作请求
	ResSafeAreaCoordEnterViewMessage = 102133,						//特效进入视野
	ReqMoonIslandRandomTransferMessage = 102135,						//土著传送
	ResMapBossMessage = 102139,						//本地图boss信息
	ResWeatherChangeMessage = 102142,						//天气改变
	SmallViewTeammateNtfMessage = 102148,						//队友小地图通知
	MonsterAppearanceChangedNtfMessage = 102149,						//怪物视野相关参数改变
	NpcsStatNtfMessage = 102150,						//Npc状态信息通知
	PlayerStateNtfMessage = 102151,						//人物状态信息通知
	ResPetShapeChangeNtf = 102152,						//宠物外形改变（或者速度改变通知）
	MapBossInfoReqMessage = 102155,						//当前地图boss信息(客户端小地图显示图标)
	TongBuQiDataReqMessage = 102157,						//同步器数据请求
	CSRandomMapMessage = 102158,						//随机地图
	CSBackCityMessage = 102159,						//回城
	SCMapDetailsMessage = 102160,						//地图详情（目前只有当前人数）
	SCGoldKeyPickUpItemMessage = 102161,						//金钥匙捡的道具
	SCMainTaskTransmitEventMessage = 102162,						//可以显示的主线任务传送点
	SCAddMainTaskTransmitEventMessage = 102163,						//添加可以显示的主线任务传送点
	SCRemoveMainTaskTransmitEventMessage = 102164,						//移除可以显示的主线任务传送点
	CSRecoverHpMessage = 102165,						//NPC回血回蓝
	#endregion
	#region bag
	ReqGetBagInfoMessage = 103101,						//获取背包信息
	ResGetBagInfoMessage = 103102,						//发送背包信息
	ResBagItemChangedMessage = 103103,						//背包物品变动信息
	ResWealthAmountChangeMessage = 103104,						//金钱变动
	ReqEquipItemMessage = 103105,						//穿装备请求
	ResEquipItemMessage = 103106,						//穿装备请求
	ReqSortItemsMessage = 103107,						//整理背包请求
	ResSortItemsMessage = 103108,						//整理背包响应
	ReqSwapItemMessage = 103109,						//交换物品格子请求
	ResSwapItemMessage = 103110,						//交换物品格子响应
	ReqUnEquipItemMessage = 103111,						//脱装备请求
	ResUnEquipItemMessage = 103112,						//脱装备响应
	ReqDestroyItemMessage = 103113,						//销毁物品请求
	ReqUseItemMessage = 103114,						//使用物品请求
	ReqCallBackItemMessage = 103115,						//回收物品请求
	ResCallBackItemMessage = 103116,						//回收物品响应
	ReqPickupItemMessage = 103130,						//拾取物品请求
	ResPickupItemMessage = 103131,						//拾取物品响应
	ResBagIsFullMessage = 103134,						//自动购买,自动使用背包已满响应
	ReqBagToStorehouseMessage = 103135,						//背包到仓库的请求
	ResBagToStorehouseMessage = 103136,						//背包到仓库的响应
	ResOpenDebugMsgMessage = 103153,						//开启调试信息
	ResChangeBagCountMessage = 103177,						//背包扩容
	ReqSplitBagItemMessage = 103178,						//拆分物品请求
	ItemUseLimitNtfMessage = 103207,						//物品使用限制下发
	LimitItemInfoNtfMessage = 103215,						//物品使用上限情况下发
	EquipItemModifyNBValueReqMessage = 103218,						//玩家属性改变
	EquipItemModifyNBValueNtfMessage = 103219,						//玩家属性改变
	AddBagCountReqMessage = 103230,						//增加背包格子请求
	EquipRebuildReqMessage = 103235,						//装备重铸请求
	EquipRebuildNtfMessage = 103236,						//装备重铸请求
	EquipXiLianReqMessage = 103237,						//装备洗炼请求
	EquipXiLianNtfMessage = 103238,						//装备洗炼响应
	CSChooseXiLianResultReqMessage = 103240,						//玩家选定最终洗炼结果的请求
	SCChooseXiLianResultNtfMessage = 103241,						//响应给玩家的最终信息
	SCNotifyBagItemCdInfoMessage = 103242,						//响应给玩家的cd信息
	ReqEquipAutoRebuildMessage = 103243,						//自动重铸到指定品质
	SCItemUsedDailyMessage = 103244,						//每日道具使用次数，使用道具时，响应
	SCItemUsedDailyTotalMessage = 103245,						//登录时，推送玩家每日道具使用次数情况，总的，响应
	#endregion
	#region tip
	ResTipMessage = 104101,						//提示信息
	ResBulletinMessage = 104102,						//公告信息
	TipNtfMessage = 104103,						//多国语言版提示信息
	SCNotifyNoteInfoMessage = 104110,						//客户端信息栏提示信息
	#endregion
	#region fight
	ReqUseSkillMessage = 105101,						//使用技能请求
	ResSkillEffectMessage = 105102,						//技能效果
	ResAddBufferMessage = 105103,						//加buff
	ResRemoveBufferMessage = 105104,						//buff消失
	ResBufferDeltaHPMessage = 105106,						//buffer造成的持续伤害或持续治疗
	SCAddSkillMessage = 105107,						//添加技能
	SCRemoveSkillMessage = 105108,						//删除技能
	ReqSaveSkillShortCutMessage = 105111,						//保存技能快捷方式请求
	SCSkillShortCutMessage = 105112,						//发送技能快捷方式回应
	ReqSetPkModeMessage = 105113,						//设置pk模式请求
	ResBufferInfoMessage = 105114,						//buff值改变
	ResRemoveSkillMessage = 105115,						//技能消失响应
	PkModeChangedNtfMessage = 105121,						//玩家PK模式变更通知
	CSUpgradeSkillMessage = 105124,						//技能升级请求
	SCUpgradeSkillMessage = 105125,						//技能升级响应
	BufferRemoveRemindNtfMessage = 105132,						//buff消失提醒
	ClearSkillCDNtfMessage = 105133,						//清除技能CD通知
	CSSetSkillAutoStateMessage = 105134,						//设置技能自动状态
	SCSetSkillAutoStateMessage = 105135,						//设置技能自动状态回应
	SCUpdateSkillRefixMessage = 105136,						//技能等级修正数据
	SCPlayerFsmStateMessage = 105137,						//玩家状态机消息
	#endregion
	#region gm
	ReqGMCommandMessage = 107101,						//gm命令请求
	ReqCloseServerMessage = 107102,						//关闭服务器请求
	ResCloseServerMessage = 107103,						//关闭服务器响应
	ReqReloadScriptMessage = 107104,						//热更脚本请求
	ResReloadScriptMessage = 107105,						//热更脚本响应
	#endregion
	#region mail
	ReqGetMailListMessage = 122101,						//获取邮件列表请求
	ResMailListMessage = 122102,						//邮件列表响应
	ResNewMailMessage = 122103,						//新邮件响应
	ReqReadMailMessage = 122104,						//标记为已读请求
	ReqGetMailItemMessage = 122105,						//提取物品请求
	ResGetMailItemMessage = 122106,						//提取物品响应
	ReqDeleteMailMessage = 122107,						//删除邮件请求
	ResDeleteMailMessage = 122108,						//删除邮件响应
	#endregion
	#region player
	ResRoleExpUpdatedMessage = 108101,						//玩家经验值变化
	ResRoleUpgradeMessage = 108102,						//玩家升级
	ReqGetRoleExtraValuesMessage = 108109,						//获取玩家额外变量请求
	ResRoleExtraValuesMessage = 108110,						//获取玩家额外变量响应
	ResDayPassedMessage = 108111,						//每日数据更新
	ReqSaveRoleSettingsMessage = 108115,						//保存玩家设置
	ReqGetOtherPlayerInfoMessage = 108122,						//获取其他玩家详情请求
	ResOtherPlayerInfoMessage = 108123,						//其他玩家的信息
	ReqSaveNewbieGuideMessage = 108124,						//保存新手引导步骤请求
	ReqGetDownloadRewardMessage = 108132,						//领取下载奖励请求
	ResCommonMessage = 108138,						//返回客户端通用消息
	ReqCommonMessage = 108139,						//客户端请求通用消息
	ResOtherPlayerCommonInfoMessage = 108140,						//客户端查看别的玩家的通用信息响应
	ReqBackServerMessage = 108146,						//返回游戏服务器请求
	RoleAttrNtfMessage = 108196,						//角色属性变更通知
	ResPlayerDieMessage = 108197,						//玩家死亡相关信息
	ResPkValueUpdateMessage = 108198,						//pk值变化
	CSUpdateNameMessage = 108134,						//用户更改姓名
	SCRoleBriefMessage = 108135,						//用户更改姓名，响应
	SCPkValueChangeMessage = 108136,						//pk值变化
	SCPkGreyNameStateMessage = 108137,						//灰名状态变化
	#endregion
	#region paodian
	ReqUpgradePaoDianMessage = 191101,						//升级泡点神符
	ResUPaoDianChangeMessage = 191102,						//泡点神符阶级星级变化
	SCPaoDianInfoMessage = 191103,						//泡点神符星级
	SCRandomPaoDianMessage = 191104,						//随机泡点位置
	SCPaoDianExpMessage = 191106,						//当前站的泡点位置
	#endregion
	#region chat
	ReqChatMessage = 109101,						//聊天请求
	ResChatMessage = 109102,						//聊天消息
	LeftCornerTipNtfMessage = 109103,						//左下角提示信息
	ReleaseReqMessage = 109104,						//语音发布请求
	ReleaseNtfMessage = 109105,						//语音发布响应
	JoinVoiceRoomReqMessage = 109106,						//请求加入语音房间
	VoiceRoomNtfMessage = 109107,						//返回语音房间情况
	LeaveVoiceRoomReqMessage = 109108,						//请求离开语音房间
	VoiceRoomNumReqMessage = 109109,						//请求语音房间人数
	RoleDetailReqMessage = 109110,						//角色详情请求
	RoleDetailNtfMessage = 109111,						//角色详情响应
	InformReqMessage = 109112,						//举报请求
	ForbidChatNtfMessage = 109113,						//禁言通知
	BigExpressionReqMessage = 109114,						//大表情请求
	BigExpressionNtfMessage = 109115,						//大表情响应
	#endregion
	#region team
	ReqCreateTeamMessage = 115101,						//创建队伍请求
	ResTeamInfoMessage = 115102,						//队伍信息
	ReqApplyTeamMessage = 115103,						//加入队伍请求
	ResApplyTeamMessage = 115104,						//队长收到的申请消息
	ReqConfirmTeamApplyMessage = 115105,						//审核队伍请求
	ReqInviteTeamMessage = 115106,						//邀请组队请求
	ResInviteTeamMessage = 115107,						//被邀请者收到的消息
	ReqConfirmTeamInviteMessage = 115108,						//审核组队邀请
	ResJoinTeamMessage = 115109,						//加入队伍响应
	ResLeaveTeamMessage = 115110,						//离开队伍响应
	ReqChangeTeamLeaderMessage = 115111,						//转让队长请求
	ResTeamLeaderChangedMessage = 115112,						//队长变更响应
	ReqLeaveTeamMessage = 115113,						//退队或踢人请求
	ReqGetTeamInfoMessage = 115114,						//请求组队面板信息
	ResGetTeamInfoMessage = 115115,						//组队面板信息响应
	ReqSetTeamModeMessage = 115116,						//设置组队模式请求
	ReqGetTeamTabMessage = 115117,						//获取组队面板tab请求
	ResGetTeamTabMessage = 115118,						//组队面板tab响应
	ReqDisposeTeamsMessage = 115120,						//解散队伍请求
	ResTeamCallBackMessage = 115121,						//帮会召唤令响应
	ReqTeamCallBackInfoMessage = 115122,						//帮会召唤令请求
	TeamTargetReqMessage = 115123,						//队伍目标请求
	TeamTargetAckMessage = 115124,						//队伍目标响应
	UnionJoinTeamReqMessage = 115125,						//家族拉取玩家加入队伍
	TeamCallBackAckMessage = 115126,						//队伍令使用响应
	SCSetTeamModeMessage = 115127,						//设置组队模式回应
	SCPlayerHpMpInfoMessage = 115128,						//发送玩家血量信息
	SCPlayerLevelInfoMessage = 115129,						//发送玩家等级信息
	#endregion
	#region instance
	ReqEnterInstanceMessage = 111101,						//进入副本
	ReqGetInstanceRewardMessage = 111102,						//获取副本奖励
	ReqBuyInstanceTimesMessage = 111103,						//购买副本次数
	ResBuyInstanceTimesMessage = 111104,						//购买副本次数响应
	ReqLeaveInstanceMessage = 111105,						//离开副本
	ResInstanceInfoMessage = 111106,						//副本信息
	SCEnterInstanceMessage = 111107,						//进入副本信息
	SCInstanceFinishMessage = 111108,						//副本结束信息
	SCLeaveInstanceMessage = 111109,						//离开副本信息
	ReqEnterNextInstanceMessage = 111111,						//进入下一层请求
	ReqQuickInstanceRewardMessage = 111135,						//快速完成副本请求
	ResQuickInstanceMessage = 111136,						//快速完成副本请求
	ResInstanceCountMessage = 111171,						//副本次数
	ResDiLaoInfoMessage = 111172,						//地牢波数信息
	ReqDiLaoGuWuMessage = 111173,						//地牢鼓舞
	SCSuiJiDuoBaoMessage = 111174,						//随机夺宝
	SCUndergroundTreasureMessage = 111180,						//地下寻宝副本信息
	CSBossChallengeMessage = 111175,						//boss挑战
	SCBossChallengeMessage = 111176,						//boss挑战响应
	SCDropLimitMessage = 111177,						//每日地图、小月卡地图、大月卡地图击杀怪物限制，响应
	#endregion
	#region storehouse
	ReqGetStorehouseInfoMessage = 113101,						//获取仓库信息
	ResGetStorehouseInfoMessage = 113102,						//发送仓库信息
	ResStorehouseItemChangedMessage = 113103,						//仓库物品变动信息
	ReqSortStorehouseMessage = 113104,						//整理仓库请求
	ResSortStorehouseMessage = 113105,						//整理仓库响应
	ReqExchangeItemMessage = 113106,						//交换物品格子请求
	ResExchangeItemMessage = 113107,						//交换物品格子响应
	ReqStorehouseToBagMessage = 113108,						//仓库到背包请求
	ResStorehouseToBagMessage = 113109,						//仓库到背包响应
	ReqAddStorehouseCountMessage = 113110,						//扩大仓库请求
	ResAddStorehouseCountMessage = 113111,						//扩大仓库响应
	#endregion
	#region wolong
	CSGetWoLongInfoMessage = 112101,						//请求卧龙数据
	SCWoLongInfoMessage = 112102,						//服务器发送卧龙数据
	CSWoLongLevelUpMessage = 112103,						//卧龙等级升级
	SCWoLongLevelUpMessage = 112104,						//卧龙等级升级回应
	CSWoLongEquipXiLianMessage = 112105,						//卧龙装备洗练
	CSSkillGroupInfoMessage = 112106,						//卧龙装备激活的技能组
	SCSkillGroupInfoMessage = 112107,						//卧龙装备激活的技能组
	CSWoLongXiLianMessage = 112110,						//洗练
	SCWoLongXiLianMessage = 112111,						//通知洗练状态
	CSWoLongXiLianSelectMessage = 112112,						//洗练确定
	SCWoLongXiLianSelectMessage = 112113,						//通知洗练确定
	CSSoldierSoulInfoAwakenMessage = 112114,						//战魂觉醒
	SCSoldierSoulInfoAwakenMessage = 112115,						//战魂觉醒返回
	SCSoldierSoulInfoMessage = 112116,						//战魂觉醒数据
	#endregion
	#region task
	ReqGetTaskListMessage = 106101,						//获取任务列表
	ResTaskListMessage = 106102,						//任务列表响应
	ResTaskStateChangedMessage = 106103,						//任务状态改变
	ResTaskGoalUpdatedMessage = 106104,						//任务进度改变
	ReqAcceptTaskMessage = 106105,						//接任务请求
	ResAcceptTaskMessage = 106106,						//接任务响应
	ReqSubmitTaskMessage = 106107,						//交任务请求
	ResSubmitTaskMessage = 106108,						//交任务响应
	ReqTalkToNPCMessage = 106109,						//npc对话任务
	SCCycTaskMessage = 106110,						//循环任务列表
	CSBuyTaskMessage = 106112,						//购买任务
	ReqFlyToGoalMessage = 106111,						//直接传送请求
	ResFlyToGoalMessage = 106115,						//直接传送响应
	SCNewTaskMessage = 106116,						//新增任务
	#endregion
	#region energy
	CSEnergyInfoMessage = 110101,						//请求精力数据
	SCEnergyInfoMessage = 110102,						//服务器发送精力数据
	CSEnergyFreeGetInfoMessage = 110103,						//请求能免费领取的数据
	SCEnergyFreeGetInfoMessage = 110104,						//服务器发送能免费领取的数据
	CSGetFreeEnergyMessage = 110105,						//领取免费的精力数据
	SCGetFreeEnergyMessage = 110110,						//服务器发送的领取精力timer
	SCNotifyEnergyChangeMessage = 110106,						//服务器发送的精力变化数据
	CSGetEnergeExchangeInfoMessage = 110107,						//获取玩家兑换数据
	SCEnergyExchangeInfoMessage = 110108,						//服务器发送的玩家兑换数据
	CSExchageEnergyMessage = 110109,						//玩家兑换
	#endregion
	#region systemcontroller
	SystemFunctionStateNtfMessage = 173101,						//通知客户端功能状态
	SCRoleFunctionDataMessage = 173102,						//玩家功能开启状态数据
	CSRoleGetFunctionDataMessage = 173103,						//请求玩家功能开启状态数据
	#endregion
	#region fengyin
	SCFengYinOpenMessage = 197101,						//封印开启
	SCFengYinTimeShortenMessage = 197102,						//封印时间缩短
	SCFengYinCloseMessage = 197103,						//封印结束
	SCHuanJingOpenMessage = 197104,						//幻境信息
	SCHuanJingCloseMessage = 197105,						//幻境结束
	SCHuanJingChangeMessage = 197106,						//幻境信息
	CSHuanJingTimeMessage = 197109,						//请求幻境时间
	ResWorldLevelMessage = 197110,						//世界等级
	#endregion
	#region social
	ReqGetSocialInfoMessage = 119101,						//获取好友信息
	ResSocialInfoMessage = 119102,						//获取好友信息响应
	ReqAddRelationMessage = 119103,						//添加好友请求
	ResAddRelationMessage = 119104,						//添加好友响应
	ReqDeleteRelationMessage = 119105,						//删除好友请求
	ReqFindPlayerByNameMessage = 119106,						//好友查找请求
	ResFindPlayerByNameMessage = 119107,						//好友查找响应
	ApplyFriendNotifyMessage = 119108,						//申请好友通知
	ReqAddFriendByNameMessage = 119115,						//通过名字添加好友请求
	ReqRejectRelationsMessage = 119117,						//一键拒绝
	ResDeleteRelationMessage = 119118,						//删除好友响应
	ReqGetAllSocialInfoMessage = 119119,						//获取社会关系信息请求
	ResGetAllSocialInfoMessage = 119120,						//获取社会关系信息响应
	RejectSingleReqMessage = 119203,						//拒绝单个人请求
	RejectSingleAckMessage = 119204,						//拒绝单个人响应
	QueryLatelyTouchReqMessage = 119205,						//查询最近联系人请求
	QueryLatelyTouchAckMessage = 119206,						//查询最近联系人响应
	CSSettingSocialMessage = 119207,						//设置里的拒绝好友请求按钮
	CSSettingStrangerInfoMessage = 119208,						//设置里的拒绝陌生人消息的按钮
	SCSettingMessage = 119209,						//响应，返回设置里两个按钮的状态
	CSSettingMessage = 119210,						//登录请求 设置按钮状态
	CSSettingGuildMessage = 119211,						//设置里的拒绝行会的按钮
	#endregion
	#region shop
	SCShopBuyInfoMessage = 193101,						//商城的购买数据
	CSShopBuyItemMessage = 193102,						//商店购买请求
	SCShopBuyMessage = 193103,						//购买物品响应
	CSShopInfoMessage = 193104,						//商城数据
	SCShopInfoMessage = 193105,						//商城数据响应
	CSDailyRmbInfoMessage = 193106,						//比奇商城 今日充值金额，请求
	SCDailyRmbInfoMessage = 193107,						//比奇商城 今日充值金额，响应
	CSDuiHuanShopInfoMessage = 193108,						//兑换商城信息，请求
	SCDuiHuanShopInfoMessage = 193109,						//兑换商城信息，响应
	SCDuiHuanShopInfoByIdMessage = 193110,						//兑换商城信息，单个，响应
	CSDuiHuanItemMessage = 193111,						//兑换商城，兑换物品，请求
	CSDuiHuanQuanMessage = 193112,						//万能券兑换，请求
	#endregion
	#region luck
	ReqUseLuckOilMessage = 201101,						//请求使用祝福油
	#endregion
	#region tujian
	SCTujianInfoMessage = 195101,						//翅膀数据
	CSTujianUpLevelMessage = 195102,						//图鉴升级
	CSTujianUpQualityMessage = 195103,						//图鉴升品
	CSTujianInlayMessage = 195104,						//图鉴镶嵌
	CSActivateSlotWingMessage = 195105,						//激活槽位
	SCTujianUpLevelMessage = 195106,						//图鉴升级
	SCTujianUpQualityMessage = 195107,						//图鉴升品
	SCTujianInlayMessage = 195108,						//图鉴镶嵌
	SCActivateSlotWingMessage = 195109,						//激活槽位
	SCTujianAddMessage = 195110,						//图鉴增加
	SCTujianRemoveMessage = 195111,						//图鉴移除
	#endregion
	#region worldboss
	CSGetWorldBossActivityInfoMessage = 146101,						//请求世界boss活动信息
	SCWorldBossActivityInfoResponseMessage = 146102,						//服务器发送世界boss活动信息
	CSJoinWorldBossActivityRequestMessage = 146103,						//参与世界boss活动
	SCJoinWorldBossActivityResponseMessage = 146104,						//服务器发送参与世界boss活动结果
	SCNotifyWorldBossRankInfoMessage = 146105,						//服务器发送世界boss排行榜信息
	CSWorldBossRankInfoMessage = 146106,						//请求世界boss排行榜信息
	CSWorldBossBlessMessage = 146107,						//世界boss祝福
	SCWorldBossBlessInfoMessage = 146108,						//世界boss祝福次数信息
	CSWorldBossBossInfoMessage = 146109,						//请求世界boss信息
	SCWorldBossBossInfoMessage = 146110,						//世界boss信息
	#endregion
	#region activity
	ReqSpecialActivityRewardMessage = 202101,						//开服活动领取活动奖励
	ResActivityDataMessage = 202102,						//玩家活动数据
	ReqActivityRewardMessage = 202103,						//领取活动奖励
	SCCollectActivityDataMessage = 202104,						//符合的装备数量
	CSCollectRewardMessage = 202106,						//领取装备收集奖励
	ReqActiveRewardMessage = 202107,						//请求活跃度奖励
	ResActiveRewardMessage = 202108,						//已领取过的活跃度奖励
	ResActiveMessage = 202109,						//返回活跃度信息
	ResFengYinDataMessage = 202110,						//返回封印比拼信息
	ResSpecialActivityDataMessage = 202111,						//返回特殊活动数据信息，通用，但是需要在各自活动特殊协议之后发送
	SCBossFirstKillDatasMessage = 202113,						//获取boss首杀信息，响应
	CSSpecialActiveDataMessage = 202120,						//请求开服活动数据
	SCEquipXuanShangMessage = 202115,						//装备悬赏，响应
	ResSevenDayDataMessage = 202121,						//七日试炼活动数据
	ResEquipCompetitionMessage = 202122,						//装备竞赛数据
	SCBossKuangHuanMessage = 202116,						//boss狂欢，响应
	CSBuyYuanbaoGiftMessage = 202125,						//购买元宝礼包
	SCKillDemonMessage = 202117,						//屠魔活动，响应
	CSSevenDayDataMessage = 202126,						//请求七日活动数据
	CSSevenDayRewardMessage = 202127,						//请求七日活动奖励
	CSEquipCompetitionDataMessage = 202128,						//请求装备竞赛数据
	CSEquipCompetitionRewardMessage = 202129,						//请求装备竞赛奖励
	CSKuangHuanRewardMessage = 202118,						//boss狂欢兑换请求
	SCSpecialActivityOpenInfoMessage = 202150,						//发送开服活动状态，玩家登录时发送，跨天有变动发送，配置表有更新后数据有变动也会发送
	SCSevenLoginMessage = 202119,						//七日登录，响应
	#endregion
	#region ultimate
	CSUltimateInfoMessage = 151101,						//请求极限挑战数据
	SCUltimateInfoMessage = 151102,						//极限挑战数据
	CSResetUltimateMessage = 151103,						//重置极限挑战数据
	SCResetUltimateMessage = 151104,						//重置极限挑战数据
	SCSelectAdditionEffectMessage = 151105,						//发送增益效果属性选择
	CSSelectAdditionIndexMessage = 151106,						//选择增益效果属性
	CSRankInfoMessage = 151107,						//请求排行
	SCRankInfoMessage = 151108,						//排行
	SCSelectAdditionIndexMessage = 151109,						//选择增益效果属性反馈
	CSRefreshCardMessage = 151111,						//刷新卡片
	CSRequestCardMessage = 151112,						//请求卡片数据
	SCResponseCardMessage = 151113,						//发送卡片效果属性选择
	CSOpenCardMessage = 151114,						//翻牌
	SCOpenCardInfoMessage = 151115,						//发送翻牌结果
	CSSelectCardIndexMessage = 151116,						//选择卡片
	SCSelectCardIndexMessage = 151117,						//选择卡片回应
	SCGodBlessMessage = 151118,						//出转盘添加血量
	SCUltimatePassInfoMessage = 151119,						//通关信息
	#endregion
	#region boss
	SCBossInfoMessage = 198101,						//可击败boss列表
	CSBossInfoMessage = 198102,						//可击败boss数据
	#endregion
	#region fashion
	CSAllFashionInfoMessage = 150101,						//请求时装数据
	SCAllFashionInfoMessage = 150102,						//时装数据
	CSEquipFashionMessage = 150103,						//穿时装
	SCEquipFashionMessage = 150104,						//穿时装回应
	CSFashionStarLevelUpMessage = 150105,						//升星
	SCFashionStarLevelUpMessage = 150106,						//升星回应
	SCAddFashionMessage = 150107,						//添加时装
	SCRemoveFashionMessage = 150108,						//删除时装
	CSActiveFashionMessage = 150109,						//激活时装
	CSUnEquipFashionMessage = 150110,						//卸载时装
	SCUnEquipFashionMessage = 150111,						//卸载时装回应
	#endregion
	#region wing
	CSWingInfoMessage = 192109,						//翅膀数据
	SCWingInfoMessage = 192101,						//翅膀数据
	CSWingUpStarMessage = 192102,						//翅膀升星
	CSWingAdvanceMessage = 192103,						//翅膀进阶
	CSDressColorWingMessage = 192104,						//穿戴幻彩道具
	SCWingUpStarMessage = 192105,						//翅膀升星
	SCWingAdvanceMessage = 192106,						//翅膀进阶
	SCDressColorWingMessage = 192107,						//穿戴幻彩道具
	SCWingExpItemUseMessage = 192108,						//翅膀经验丹使用
	SCColorWingChangeMessage = 192110,						//幻彩道具变更
	SCYuLingInfoMessage = 192112,						//羽灵信息，相应
	CSYuLingUpgradeMessage = 192113,						//羽灵升级，请求
	CSYuLingSoulSetMessage = 192114,						//羽灵之魂镶嵌，请求
	CSYuLingSoulUpgradeMessage = 192115,						//羽灵之魂快捷合成，请求
	CSYuLingSoulSingleSetMessage = 192116,						//羽灵之魂、单个镶嵌，请求
	#endregion
	#region lianti
	SCLianTiInfoMessage = 194101,						//炼体数据
	CSLianTiFieldMessage = 194104,						//炼体之地
	SCLianTiFieldMessage = 194105,						//炼体之地
	CSLianTiUpLevelMessage = 194102,						//炼体升级
	SCLianTiUpLevelMessage = 194103,						//炼体升级
	#endregion
	#region auction
	ReqGetAuctionItemsMessage = 128101,						//获取商品列表请求
	ResGetAuctionItemsMessage = 128102,						//商品列表响应
	ReqGetAuctionShelfMessage = 128103,						//获取自己的上架商品列表请求
	ResGetAuctionShelfMessage = 128104,						//自己已上架商品列表响应
	ReqAddToShelfMessage = 128105,						//上架请求
	ResAddToShelfMessage = 128106,						//上架响应
	ReqReAddToShelfMessage = 128107,						//重新上架
	ResReAddToShelfMessage = 128108,						//重新上架响应
	ReqRemoveFromShelfMessage = 128109,						//下架请求
	ResRemoveFromShelfMessage = 128110,						//下架响应
	ReqBuyAuctionAuctionMessage = 128111,						//购买请求
	ResBuyAuctionItemMessage = 128112,						//购买响应
	ReqUnlockAuctionShelveMessage = 128113,						//解锁槽位
	ResUnlockAuctionShelveMessage = 128114,						//返回槽位解锁
	ReqAttentionAuctionMessage = 128115,						//关注
	ResAttentionAuctionMessage = 128116,						//返回关注列表
	ReqAuctionCryMessage = 128117,						//吆喝
	ReqCancelAttentionAuctionMessage = 128118,						//取消关注
	ReqGetAttentionAuctionMessage = 128119,						//获取关注列表
	#endregion
	#region union
	CSGetUnionInfoMessage = 114101,						//请求帮会信息
	SCGetUnionInfoMessage = 114102,						//帮会信息响应
	SCUnionListMessage = 114103,						//帮会列表响应
	CSCreateUnionMessage = 114104,						//创建帮会请求
	SCCreateUnionMessage = 114105,						//创建帮会响应
	CSApplyUnionMessage = 114106,						//请求加入
	CSInviteUnionMessage = 114107,						//邀请加入
	SCInviteUnionMessage = 114108,						//被邀请的人收到的消息
	CSChangeUnionPositionMessage = 114109,						//更改帮会职位请求
	SCUnionPositionChangedMessage = 114110,						//帮会职位变更响应
	CSLeaveUnionMessage = 114111,						//退会或踢人请求
	SCLeaveUnionMessage = 114112,						//退会或踢人响应
	CSUnionDonateGoldMessage = 114113,						//捐钱请求
	SCUnionDonateGoldMessage = 114114,						//捐钱响应
	CSUnionDonateEquipMessage = 114115,						//捐装备请求
	SCUnionDonateEquipMessage = 114116,						//捐装备响应
	SCJoinUnionMessage = 114117,						//加入帮会响应
	CSUnionExchangeEquipMessage = 114118,						//兑换装备请求
	SCUnionExchangeEquipMessage = 114119,						//兑换装备响应
	CSUnionChangePresidentMessage = 114120,						//转让会长请求
	CSDisposeUnionMessage = 114121,						//解散帮会请求
	CSConfirmUnionApplyMessage = 114122,						//审核入会请求
	CSUnionDestroyItemMessage = 114123,						//销毁物品请求
	CSUnionDeclareWarMessage = 114124,						//宣战请求
	SCUnionDeclareWarMessage = 114125,						//宣战响应
	SCUnionWarTimeoutMessage = 114126,						//宣战时间已过
	CSGetUnionTabMessage = 114127,						//获取帮会tab请求
	SCGetUnionTabMessage = 114128,						//获取帮会tab响应
	CSSendSouvenirWealthMessage = 114129,						//发红包请求
	CSGetSouvenirWealthMessage = 114130,						//抢红包请求
	SCGetSouvenirWealthMessage = 114131,						//抢到红包响应
	CSUnionBulletinMessage = 114134,						//请求提交公告
	SCUnionInfoUpdatedMessage = 114135,						//帮会信息更新响应(有人申请加入)
	CSUnionJoinInfoMessage = 114136,						//帮会申请列表请求
	SCUnionJoinInfoMessage = 114137,						//帮会申请列表响应
	CSImpeachmentMessage = 114138,						//弹劾请求
	SCImpeachementMessage = 114139,						//弹劾信息响应
	SCCanApplyUnionMessage = 114140,						//可以加入公会提示
	CSSetAutoJoinLevelMessage = 114141,						//设置自动加人等级限制请求
	SCChangeLeaderMessage = 114142,						//通知给转让会长给我
	CSSetApplyLeaderMessage = 114143,						//确定是否允许别人转让会长给我
	CSCombineUnionMessage = 114144,						//帮会合并请求
	SCQueryCombineUnionMessage = 114145,						//帮会合并询问响应
	CSUnionExchangeEquipLimitMessage = 114147,						//帮会取装备权限请求
	CSUnionRenameMessage = 114148,						//帮会改名请求
	CSPushUnionMessageMessage = 114149,						//帮会推送消息
	SCUnionBulletinAckMessage = 114150,						//修改公告成功包响应
	SCImpeachmentAckMessage = 114151,						//发起弹劾响应(客户端面板)
	SCImpeachmentEndNtfMessage = 114152,						//弹劾结束响应
	SCRoleApplyUnionMessage = 114153,						//玩家申请的帮会信息
	SCUnionRecommendAckMessage = 114154,						//推荐家族告诉客户端家族是空
	CSImproveInfosMessage = 114160,						//请求修炼数据
	SCImproveInfosMessage = 114161,						//获取修炼数据
	CSImproveMessage = 114162,						//修炼请求
	SCImproveMessage = 114163,						//回应修炼
	CSRemoveApplyUnionMessage = 114164,						//删除申请
	SCUnionDestroyItemMessage = 114165,						//销毁物品回应
	CSSplitYuanbaoMessage = 114170,						//分脏
	SCSplitYuanbaoMessage = 114171,						//分脏结果
	ResUpdateSpeakLimitsMessage = 114177,						//能否实时语音响应
	ReqUpdateSpeakLimitsMessage = 114178,						//更新实时语音请求
	ResUnionCallInfoMessage = 114179,						//行会召集令信息，发起人使用道具的响应
	ReqUnionCallInfoMessage = 114180,						//行会人员使用行会召集令，请求
	#endregion
	#region intensify
	CSIntensifyMessage = 204101,						//部位强化请求
	SCIntensifyMessage = 204102,						//部位强化响应
	SCIntensifyInfoMessage = 204103,						//部位强化信息
	SCIntensifySuitInfoMessage = 204104,						//强化套装信息
	#endregion
	#region baozhu
	CSLevelUpBaoZhuMessage = 206101,						//宝珠升级
	SCLevelUpBaoZhuMessage = 206102,						//返回宝珠升级
	CSGradeUpBaoZhuMessage = 206103,						//宝珠升阶
	SCGradeUpBaoZhuMessage = 206104,						//返回宝珠升阶
	CSRandBaoZhuSkillMessage = 206105,						//随机宝珠技能
	SCBaoZhuSkillsMessage = 206106,						//返回宝珠技能槽的技能
	CSChoseBaoZhuSkillMessage = 206107,						//替换宝珠技能
	SCChoseBaoZhuSkillMessage = 206108,						//返回替换宝珠技能
	SCBaoZhuBossCountChangeMessage = 206109,						//返回宝珠击杀boss数量变化
	SCBaoZhuSlotSkillsMessage = 206110,						//返回宝珠技能槽的技能
	#endregion
	#region sabac
	CSSabacDataInfoMessage = 160101,						//请求沙巴克数据
	SCSabacDataInfoMessage = 160102,						//服务器沙巴克数据
	SCNotifySabacStateMessage = 160103,						//广播活动状态,活动期间玩家上线也会单独发送
	CSSabacRankInfoMessage = 160104,						//请求排行榜信息
	SCSabacRankInfoMessage = 160105,						//服务器发送排行榜信息
	SCSabacResultMessage = 160106,						//sabac结束信息
	CSSabacStateMessage = 160107,						//活动状态请求
	SCSabacTransDoorInfoMessage = 160108,						//sabac传送点更新数据
	#endregion
	#region vip
	ResVipMessage = 131101,						//vip信息
	ReqDrawVipPackMessage = 131102,						//领取礼包请求
	ResVipTasteCardMessage = 131115,						//vip体验卡消息
	SCVipTasteCardMessage = 131114,						//登录推送体验卡消息
	CSDrawFirstRechargeRewardMessage = 131111,						//领取首冲礼包
	SCFirstRechargeInfoMessage = 131116,						//首次充值数据
	ReqFirstRechargeEntranceMessage = 131104,						//首充入口请求
	FirstRechargeNtfMessage = 131103,						//首次充值通知
	AccumulatedRechargeInfoMessage = 131105,						//累充信息
	CSReceiveAccumulatedRechargeRewardMessage = 131107,						//领取累充奖励
	CSMonthRechargeInfoMessage = 131108,						//月度充值，请求
	SCMonthRechargeInfoMessage = 131109,						//月度充值，响应
	CSMonthRechargeMessage = 131110,						//购买元宝，请求
	SCMonthRechargeInfoByIdMessage = 131112,						//月度充值 单个，响应
	#endregion
	#region gem
	CSEquipGemMessage = 196101,						//装备宝石
	SCPosGemChangeMessage = 196102,						//位置宝石变化
	CSUpgradePosGemMessage = 196103,						//升级身上的宝石
	SCPosGemInfoMessage = 196104,						//位置宝石信息，用于登录
	CSUnlockGemPositionMessage = 196105,						//解锁装备部位
	SCUnlockGemPositionMessage = 196106,						//解锁装备部位返回
	SCGemSuitMessage = 196107,						//宝石套装
	SCGemBossCountChangeMessage = 196108,						//boss击杀计数变化
	#endregion
	#region treasurehunt
	ReqGetTreasureHuntMessage = 129101,						//寻宝记录
	ReqPointInfoMessage = 129102,						//积分兑换记录
	ReqTreasureHuntMessage = 129103,						//寻宝请求
	ReqExchangePointMessage = 129104,						//寻宝积分兑换请求
	ResServerHistoryMessage = 129105,						//历史信息
	ReqGetItemMessage = 129106,						//取出寻宝仓库单个格子的物品
	ReqGetWholeItemMessage = 129107,						//一键取出寻宝仓库物品
	ResTreasureItemChangedMessage = 129108,						//寻宝仓库物品变动信息
	ReqTreasureStorehouseMessage = 129109,						//寻宝仓库信息请求
	ResTreasureStorehouseMessage = 129110,						//寻宝仓库信息
	ResTreasureEndMessage = 129111,						//寻宝结束信息
	ReqUseTreasureExpMessage = 129112,						//寻宝地元丹使用
	ResUseTreasureExpMessage = 129113,						//寻宝地元丹使用响应
	ReqTreasureIdMessage = 129114,						//寻宝界面宝箱请求
	ResTreasureIdMessage = 129115,						//寻宝界面宝箱响应
	ReqHuntCallBackMessage = 129118,						//寻宝仓库中回收装备请求
	ResHuntCallBackMessage = 129119,						//寻宝仓库中回收装备响应
	#endregion
	#region stonetreasure
	CSFloorInfoMessage = 210101,						//人物当前所在石阵层数请求
	SCFloorInfoMessage = 210102,						//false：未开启石阵寻宝 true：开启石阵寻宝，不管点没点
	CSStoneLocationMessage = 210103,						//击碎石块，请求
	SCStoneLocationMessage = 210104,						//击碎石块，响应
	SCDownLocationMessage = 210105,						//下一层的坐标信息，1.奖励全部领完时2.进入惊喜层时
	CSStoneMailMessage = 210106,						//发送石阵寻宝开启邮件
	SCGetNormalAndDownMessage = 210107,						//稀有、特殊、惊喜奖励领完时，返回普通奖励，下一层位置
	CSDownStoneMessage = 210108,						//进入下一层的请求
	#endregion
	#region sign
	ReqSignInfoMessage = 211101,						//请求签到信息
	ResCardInfoMessage = 211102,						//签到卡片
	ResSignInfoMessage = 211103,						//得到签到相关数据
	ReqExchangeCardMessage = 211104,						//兑换抽卡次数
	ReqChoseCardMessage = 211105,						//选择卡牌
	ResCardChangeMessage = 211106,						//卡片变化
	ReqSignComposeMessage = 211107,						//请求合成
	ReqSignAchievementMessage = 211108,						//领取成就奖励
	ResFinalSignRewardMessage = 211109,						//返回领取最终大奖
	ReqSignFragmentMessage = 211110,						//请求分解成碎片
	ResFragmentChangeMessage = 211111,						//碎片变化
	ReqLockCardMessage = 211112,						//锁定卡牌
	ResLockCardMessage = 211113,						//返回锁定卡牌
	ReqUnLockCardMessage = 211114,						//解除锁定卡牌
	ResCollectionChangeMessage = 211115,						//组合变化
	ResHonorChangeMessage = 211116,						//成就变化
	#endregion
	#region wildadventure
	CSWildAdventrueMessage = 213101,						//野外冒险
	SCWildAdventrueMessage = 213102,						//野外冒险
	CSTakeOutItemMessage = 213103,						//取出道具
	SCTakeOutItemMessage = 213104,						//取出道具
	SCBossItemMessage = 213105,						//boss掉落
	#endregion
	#region rank
	ResRankInfoMessage = 199101,						//排行榜列表
	ReqRankInfoMessage = 199102,						//请求排行榜数据
	#endregion
	#region daycharge
	CSDayChargeInfoMessage = 161101,						//请求每日充值数据
	SCDayChargeInfoMessage = 161102,						//回应每日充值数据
	CSDayChargeRewardGetMessage = 161103,						//领取奖励
	SCDayChargeRewardGetMessage = 161104,						//领取奖励回应
	#endregion
	#region combine
	CSCombineItemMessage = 203101,						//合成请求
	SCCombineItemMessage = 203102,						//合成响应
	#endregion
	#region monthcard
	CSBuyMonthCardMessage = 205101,						//月卡购买请求
	SCBuyMonthCardMessage = 205102,						//月卡购买响应
	SCMonthCardInfoMessage = 205103,						//月卡数据
	CSReceiveMonthCardRewardMessage = 205104,						//领取月卡奖励
	SCReceiveMonthCardRewardMessage = 205105,						//领取月卡奖励响应
	#endregion
	#region dailypurchase
	SCDailyPurchaseInfoMessage = 200101,						//每日限购信息的购买数据
	CSDailyPurchaseBuyMessage = 200102,						//购买请求
	SCDailyPurchaseBuyMessage = 200103,						//购买响应
	SCEquipCompetitionPurchaseInfoMessage = 200104,						//装备竞赛购买数据
	SCZhiGouInfoMessage = 200105,						//直购礼包信息
	SCZhiGouOrderMessage = 200106,						//直购礼包充值订单号
	SCGiftBagInfoMessage = 200107,						//giftbag表活动信息
	SCGiftBagOpenMessage = 200108,						//giftbag表活动开启
	SCGiftBagCloseMessage = 200109,						//giftbag表活动关闭
	CSLookGiftMessage = 200110,						//查看礼包
	SCLookGiftMessage = 200111,						//查看礼包返回
	CSLookPositionMessage = 200112,						//查看页签
	SCLookPositionMessage = 200113,						//查看页签返回
	#endregion
	#region lifelongfund
	CSReceiveFundRewardMessage = 212101,						//领取基金奖励
	SCReceiveFundRewardMessage = 212105,						//基金数据
	SCLifelongFundInfoMessage = 212102,						//基金数据
	CSBuylifelongFundMessage = 212103,						//购买终身基金
	CSReceiveFundTaskRewardMessage = 212104,						//领取基金奖励
	SCFundTaskInfoChangeMessage = 212106,						//任务改变
	#endregion
	#region rankalonetable
	SCRoleRankInfoMessage = 214101,						//角色排行榜列表
	CSRoleRankInfoMessage = 214102,						//请求排行榜数据
	SCUnionRankInfoMessage = 214103,						//公会排行榜列表
	#endregion
	#region gameversion
	ClientVersionNtfMessage = 175101,						//通知客户端版本号
	ClientUpdateNtfMessage = 175102,						//通知客户端更新
	#endregion
	#region pet
	SCPetHpMessage = 180105,						//宠物血量信息
	SCWoLongPetActiveMessage = 180106,						//激活卧龙战魂
	SCNotifyWoLongPetStateMessage = 180108,						//通知卧龙战宠状态
	CSWoLongPetChangeStateMessage = 180109,						//卧龙战宠改变状态,出战,合体
	CSWoLongPetInfoMessage = 180117,						//卧龙战宠信息
	SCWoLongPetInfoMessage = 180118,						//发送卧龙战宠信息
	SCPlayerWoLongViewInfoMessage = 180119,						//视野卧龙战宠信息
	CSPetInfoMessage = 180120,						//战宠信息，请求
	SCPetInfoMessage = 180121,						//战宠信息，响应
	CSPetUpgradeMessage = 180122,						//战宠升级，请求
	SCItemCallBackInfoMessage = 180123,						//宠物升级，吞噬装备后获得的道具的详情，响应
	CSPetSkillUpgradeMessage = 180124,						//宠物技能升级，请求
	CSUnlockPetTianFuMessage = 180125,						//解锁宠物天赋
	SCPetTianFuInfoMessage = 180126,						//宠物天赋信息
	SCPetSkillUpgradeMessage = 180127,						//宠物技能升级，响应
	SCPetTianFuPassiveSkillMessage = 180128,						//宠物天赋被动技能信息
	CSPetTianFuRandomPassiveSkillMessage = 180129,						//宠物天赋随机被动技能
	SCPetTianFuRandomPassiveSkillMessage = 180130,						//返回宠物天赋随机被动技能
	CSPetTianFuChosePassiveSkillMessage = 180131,						//宠物天赋注入被动技能
	SCPetTianFuChosePassiveSkillMessage = 180132,						//宠物天赋注入被动技能
	SCPetTianFuChangeMessage = 180133,						//宠物天赋变化
	SCPetHejiPointMessage = 180134,						//宠物合击能量点变化
	SCPetActivePvpMessage = 180135,						//激活pvp广播周边
	SCCallBackSettingMessage = 180136,						//回收设置信息，响应
	CSSetCallBackSettingMessage = 180137,						//存储回收设置信息，请求
	#endregion
	#region athleticsactivity
	CSAthleticsActivityInfoMessage = 216101,						//竞技活动信息
	SCAthleticsActivityInfoMessage = 216102,						//竞技活动信息
	CSReceiveAthleticsActivityRewardMessage = 216103,						//领取竞技活动奖励
	SCReceiveAthleticsActivityRewardMessage = 216104,						//领取竞技活动奖励
	ActivityRewardInfoChangeNotify = 216105,						//竞技活动奖励信息变更
	#endregion
	#region mafa
	ResMafaInfoMessage = 217101,						//玛法相关信息
	ResMafaExpChangeMessage = 217102,						//玛法经验条变化信息
	ReqMafaLayerRewardMessage = 217103,						//请求获得玛法层奖励
	ResMafaLayerChangeMessage = 217104,						//玛法层变化信息
	ResMafaSuperLayerUnlockMessage = 217106,						//高级层解锁
	ReqMafaBoxRewardMessage = 217107,						//请求打开宝箱
	ResMafaBoxRewardMessage = 217108,						//返回打开宝箱
	#endregion
	#region code
	CSCodeMessage = 215101,						//激活码，请求
	SCCodeRewardMessage = 215102,						//获取激活码，响应
	#endregion
	#region memory
	ResMemoryInstanceInfoMessage = 219101,						//回忆秘境信息
	ResMemoryBagMessage = 219102,						//怀旧装备背包
	ResMemoryEquipInfoMessage = 219103,						//身上穿的怀旧装备
	ResMemoryAddMessage = 219104,						//获得怀旧装备
	ResMemoryEquipChangeMessage = 219105,						//身上穿的怀旧装备变化
	ResMemoryEquipSuitMessage = 219106,						//怀旧装备套装
	ReqPutOnMemoryEquipMessage = 219107,						//穿戴怀旧装备
	ReqMemoryEquipLevelUpMessage = 219108,						//怀旧装备升级
	ReqUnlockMemoryEquipGeziMessage = 219110,						//解锁格子
	ResMemoryEquipGeziChangeMessage = 219111,						//格子变化
	ResMemoryRemoveMessage = 219112,						//移除怀旧装备
	ReqDiscardMemoryEquipMessage = 219113,						//丢弃装备
	ResDiscardMemoryEquipMessage = 219114,						//返回丢弃装备
	ReqMemorySummonTeamMessage = 219115,						//召唤队员
	ResMemorySummonTeamMessage = 219116,						//通知其他队员，召唤队员
	ReqMemoryGotoSummonMessage = 219117,						//响应召唤
	ResMemorySummonTeamCdMessage = 219118,						//召唤队员CD
	#endregion
	#region unionbattle
	SCUnionActivityInfoMessage = 218101,						//公会活动
	SCUnionActivityInfoChangeMessage = 218102,						//公会活动状态变更
	SCLastUnionRankMessage = 218103,						//上次公会战排行
	SCUnionActivityRewardMessage = 218104,						//公会战奖励弹框数据
	CSUnionActivityInfoMessage = 218105,						//公会活动
	#endregion
	#region yuanbao
	ResYuanBaoInfoMessage = 220101,						//元宝信息
	#endregion
}
