// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resourceList.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using scg = global::System.Collections.Generic;
namespace TABLE {

  #region Messages
  public sealed class RESOURCELIST : pb::IMessage {
    private static readonly pb::MessageParser<RESOURCELIST> _parser = new pb::MessageParser<RESOURCELIST>(() => new RESOURCELIST());
    public static pb::MessageParser<RESOURCELIST> Parser { get { return _parser; } }

    private string name_ = "";
    /// <summary>
    ///名称
    /// </summary>
    public string name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    private int length_;
    /// <summary>
    ///长度
    /// </summary>
    public int length {
      get { return length_; }
      set {
        length_ = value;
      }
    }

    private string resType_ = "";
    /// <summary>
    ///资源类型
    /// </summary>
    public string resType {
      get { return resType_; }
      set {
        resType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    private string md5_ = "";
    /// <summary>
    ///MD5
    /// </summary>
    public string md5 {
      get { return md5_; }
      set {
        md5_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(name);
      }
      if (length != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(length);
      }
      if (resType.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(resType);
      }
      if (md5.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(md5);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(name);
      }
      if (length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(length);
      }
      if (resType.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(resType);
      }
      if (md5.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(md5);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            name = input.ReadString();
            break;
          }
          case 16: {
            length = input.ReadInt32();
            break;
          }
          case 26: {
            resType = input.ReadString();
            break;
          }
          case 34: {
            md5 = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed class RESOURCELISTARRAY : pb::IMessage {
    private static readonly pb::MessageParser<RESOURCELISTARRAY> _parser = new pb::MessageParser<RESOURCELISTARRAY>(() => new RESOURCELISTARRAY());
    public static pb::MessageParser<RESOURCELISTARRAY> Parser { get { return _parser; } }

    private static readonly pb::FieldCodec<global::TABLE.RESOURCELIST> _repeated_rows_codec
        = pb::FieldCodec.ForMessage(10, global::TABLE.RESOURCELIST.Parser);
    private readonly pbc::RepeatedField<global::TABLE.RESOURCELIST> rows_ = new pbc::RepeatedField<global::TABLE.RESOURCELIST>();
    public pbc::RepeatedField<global::TABLE.RESOURCELIST> rows {
      get { return rows_; }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      rows_.WriteTo(output, _repeated_rows_codec);
    }

    public int CalculateSize() {
      int size = 0;
      size += rows_.CalculateSize(_repeated_rows_codec);
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            rows_.AddEntriesFrom(input, _repeated_rows_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
