// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resourceListAndroid.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using scg = global::System.Collections.Generic;
namespace TABLE {

  #region Messages
  public sealed class RESLISTANDROID : pb::IMessage {
    private static readonly pb::MessageParser<RESLISTANDROID> _parser = new pb::MessageParser<RESLISTANDROID>(() => new RESLISTANDROID());
    public static pb::MessageParser<RESLISTANDROID> Parser { get { return _parser; } }

    private string name_ = "";
    /// <summary>
    ///名称
    /// </summary>
    public string name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    private string md5_ = "";
    /// <summary>
    ///MD5
    /// </summary>
    public string md5 {
      get { return md5_; }
      set {
        md5_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    private string server_ = "";
    /// <summary>
    ///服务器类型， 0：普通服， 1：先行服
    /// </summary>
    public string server {
      get { return server_; }
      set {
        server_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(name);
      }
      if (md5.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(md5);
      }
      if (server.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(server);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(name);
      }
      if (md5.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(md5);
      }
      if (server.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(server);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            name = input.ReadString();
            break;
          }
          case 18: {
            md5 = input.ReadString();
            break;
          }
          case 26: {
            server = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed class RESLISTANDROIDARRAY : pb::IMessage {
    private static readonly pb::MessageParser<RESLISTANDROIDARRAY> _parser = new pb::MessageParser<RESLISTANDROIDARRAY>(() => new RESLISTANDROIDARRAY());
    public static pb::MessageParser<RESLISTANDROIDARRAY> Parser { get { return _parser; } }

    private static readonly pb::FieldCodec<global::TABLE.RESLISTANDROID> _repeated_rows_codec
        = pb::FieldCodec.ForMessage(10, global::TABLE.RESLISTANDROID.Parser);
    private readonly pbc::RepeatedField<global::TABLE.RESLISTANDROID> rows_ = new pbc::RepeatedField<global::TABLE.RESLISTANDROID>();
    public pbc::RepeatedField<global::TABLE.RESLISTANDROID> rows {
      get { return rows_; }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      rows_.WriteTo(output, _repeated_rows_codec);
    }

    public int CalculateSize() {
      int size = 0;
      size += rows_.CalculateSize(_repeated_rows_codec);
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            rows_.AddEntriesFrom(input, _repeated_rows_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
