// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Luck.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using scg = global::System.Collections.Generic;
namespace luck {

  #region Messages
  public sealed class UseLuckOil : pb::IMessage {
    private static readonly pb::MessageParser<UseLuckOil> _parser = new pb::MessageParser<UseLuckOil>(() => new UseLuckOil());
    public static pb::MessageParser<UseLuckOil> Parser { get { return _parser; } }

    private int index_;
    /// <summary>
    ///装备位置
    /// </summary>
    public int index {
      get { return index_; }
      set {
        index_ = value;
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (index != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(index);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (index != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(index);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            index = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
